[project]
name = "sandbox-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "sortedcontainers>=2.4.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.13",
]
